Win_CI:
    variables:
        GIT_SUBMODULE_STRATEGY: normal
    stage: build
    script:
        - git lfs env
        - git lfs install
        - git submodule init
        - git submodule update
        - rmdir stage /s /q
        - rmdir build /s /q
        - mkdir build
        - cd build
        - cmake -G "MinGW Makefiles" ../ -DCMAKE_BUILD_TYPE="Release" -DCMAKE_INSTALL_PREFIX=../stage -DBUILD_TESTS=ON -DINSTALL_DEPS=ON -DENABLE_LOG=OFF
        - cmake --build . --target install
        - cd ..
        - rmdir stage /s /q
        - rmdir build /s /q
        - mkdir build
        - cd build
        - cmake -G "MinGW Makefiles" ../ -DCMAKE_BUILD_TYPE="Release" -DCMAKE_INSTALL_PREFIX=../stage -DBUILD_TESTS=ON -DINSTALL_DEPS=ON -DENABLE_LOG=ON
        - cmake --build . --target install
        - ctest --verbose
    only:
        - v0.6.x
        - v0.7.x
        - v0.9.x
    tags:
        - WIN

CentOS_CI:
    variables:
        GIT_SUBMODULE_STRATEGY: normal
    stage: build
    script: 
        - git submodule init
        - git submodule update
        - source /opt/rh/devtoolset-7/enable
        - source /opt/rh/python27/enable
        - source /opt/rh/rh-python35/enable
        - rm -rf stage
        - rm -rf build
        - mkdir -p build
        - cd build
        - cmake ../ -DCMAKE_BUILD_TYPE="Release" -DCMAKE_INSTALL_PREFIX=../stage -DBUILD_TESTS=ON -DENABLE_LOG=OFF -DINSTALL_DEPS=ON
        - cmake --build . --target install
        - cd ..
        - rm -rf stage
        - rm -rf build
        - mkdir -p build
        - cd build
        - cmake ../ -DCMAKE_BUILD_TYPE="Release" -DCMAKE_INSTALL_PREFIX=../stage -DBUILD_TESTS=ON -DENABLE_LOG=ON -DINSTALL_DEPS=ON
        - cmake --build . --target install
        - ctest --verbose
    only:
        - v0.6.x
        - v0.7.x
        - v0.9.x
    tags:
        - CENTOS
