build_and_test_centos:
    stage: build_and_test
    script: 
        - source /opt/rh/devtoolset-6/enable
        - source /opt/rh/python27/enable
        - source /opt/rh/rh-python35/enable
        - git submodule init
        - git submodule update
        - rm -rf stage
        - mkdir -p build
        - cd build
        - cmake --build . --target clean || true 
        - cmake ../ -DCMAKE_BUILD_TYPE="Release" -DCMAKE_INSTALL_PREFIX=../stage -DBUILS_TESTS=ON
        - cmake --build . --target install
    only:
        - master
    tags:
        - CENTOS
