Win_CI:
    stage: build
    script: 
        - git submodule init
        - git submodule update
        - rmdir stage /s /q
        - mkdir build
        - cd build
        - cmake --build . --target clean
        - cmake -G "MinGW Makefiles" ../ -DCMAKE_BUILD_TYPE="Release" -DCMAKE_INSTALL_PREFIX=../stage -DBUILS_TESTS=ON -DINSTALL_DEPS=ON
        - cmake --build . --target install
    only:
        - master
    tags:
        - WIN

CentOS_CI:
    stage: build
    script: 
        - source /opt/rh/devtoolset-6/enable
        - source /opt/rh/python27/enable
        - source /opt/rh/rh-python35/enable
        - git submodule init
        - git submodule update
        - rm -rf stage
        - mkdir -p build
        - cd build
        - cmake --build . --target clean || true 
        - cmake ../ -DCMAKE_BUILD_TYPE="Release" -DCMAKE_INSTALL_PREFIX=../stage -DBUILS_TESTS=ON
        - cmake --build . --target install
    only:
        - master
    tags:
        - CENTOS
