option( ENABLE_CPACK "Enables cpack rules" ON )
option( BUILD_SHARED_LIBS "Build shared library" OFF )
option( BUILD_TESTS "Build tests" ON)
option( INSTALL_DEPS "Install upstream dependencies" OFF)
option( ENABLE_LOG "Enable chipimgproc internal log" ON)
option( BUILD_DOC "Build document" OFF)
option( COPY_ALL_TP "Copy all third party library into <install-prefix>/third_party" OFF)
