option( ENABLE_CPACK "Enables cpack rules" ON )
option( BUILD_SHARED_LIBS "Build shared library" OFF )
option( BUILD_TESTS "Build tests" ON)
option( INSTALL_DEPS "Install upstream dependencies" OFF)
if("${CMAKE_BUILD_TYPE}" STREQUAL "Release")
    set(ENABLE_LOG_DEFAULT OFF)
else() 
    set(ENABLE_LOG_DEFAULT ON)
endif()
option( ENABLE_LOG "enable chipimgproc internal log" ${ENABLE_LOG_DEFAULT})